### ISSUE TITLE
SdlManagerListener managerShouldUpdateLifecycle has no return

### ISSUE THREAD

**Issue by crokita** [smartdevicelink/sdl_javascript_suite#221]
##### Expected Behavior
`SdlManagerListener.managerShouldUpdateLifecycle` should match the signature of the other libraries.

##### Observed Behavior
There is no return value for `managerShouldUpdateLifecycle`. It should return a `LifecycleConfigurationUpdate` object.

**Comment by vladmu** [comment]
@crokita I have found additional issues here:
1. When the `RegisterAppInterface` request is sent, no any `catch` followed by this
https://github.com/smartdevicelink/sdl_javascript_suite/blob/965b3bd7a6cfa6912b94d3de92a6763dfca0fb91/lib/js/src/manager/lifecycle/_LifecycleManager.js#L111-L113 That leads to `Uncaught (in promise)` error
![image](https://user-images.githubusercontent.com/2202092/81963950-974fdc00-961e-11ea-8b28-4fd39e5ea3a4.png)
because the promise `sendRpcMessage` rejects any `resultCode` excluding `SUCCESS` and `WARNINGS`
https://github.com/smartdevicelink/sdl_javascript_suite/blob/965b3bd7a6cfa6912b94d3de92a6763dfca0fb91/lib/js/src/manager/lifecycle/_LifecycleManager.js#L247-L255
So the `WRONG_LANGUAGE` result code has this uncaught exception.
2. `LifecycleConfigurationUpdate` object is missing in the library
3. In this line of code, the `ChangeRegistration` is initiated with 2 parameters, but the RPC class could accept only the object map of parameters. 
https://github.com/smartdevicelink/sdl_javascript_suite/blob/965b3bd7a6cfa6912b94d3de92a6763dfca0fb91/lib/js/src/manager/SdlManager.js#L232
4. As a followup of point 2 the `RPC.msg_params: Missing mandatory parameter: hmiDisplayLanguage` error occurs after the RPC request is sent because setter of this parameter is not called in the code
https://github.com/smartdevicelink/sdl_javascript_suite/blob/965b3bd7a6cfa6912b94d3de92a6763dfca0fb91/lib/js/src/manager/SdlManager.js#L232-L237

**Comment by vladmu** [comment]
@crokita I've created the PR #223 with fixes of all described above.

**Comment by theresalech** [comment]
Closed via #223
