### ISSUE TITLE
Wrong branch name is used for rpc_spec submodule

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_javascript_suite#328]
**Bug Report**
Wrong branch name is used for rpc_spec submodule

All opensource repositories which have dependency on **rpc_spec** submodule must be aligned and use the same branch for releases
By that reason **.gitmodule** file of this repository should be aligned with SDL: https://github.com/smartdevicelink/sdl_core/blob/develop/.gitmodules
Additionally, by that reason example applications from that repository will not be able to use the latest API and latest SDL features

**Comment by AKalinich-Luxoft** [comment]
@crokita could you please advice should this issue be fixed for current repository for develop branch?

**Comment by crokita** [comment]
Hello. For all my development I change to the develop rpc_spec branch for my local git client but don't commit that change to GitHub. If the commit is pushed to change the submodule to develop then we would need another commit to change the rpc_spec branch back to master when ready for release. I would be okay with that, but since this was brought up so close to the testing phase of the JS suite, I don't think there would be much value in making it a committed change to GitHub at this time. This is something that we can keep in mind for next release 👍
